# Generated by Django 3.2.13 on 2022-05-26 17:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0024_delete_proctoredexamstudentattempthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockProviderConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('base_url', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
